name: Lint

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - '.vscode/**'

jobs:
  lint:
    runs-on: ubuntu-24.04
    timeout-minutes: 3
    permissions:
      contents: read
      pull-requests: write
    strategy:
      matrix:
        env: [src]
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'npm'
      - run: npm ci
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      # 本記事のメイン
      - name: Run reviewdog with eslint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          filter_mode: diff_context
          fail_level: error
          workdir: ${{ matrix.env }}